DROP TABLE IF EXISTS prices;
  
CREATE TABLE prices (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  BRAND_ID SMALLINT,
  START_DATE TIMESTAMP DEFAULT NULL,
  END_DATE TIMESTAMP DEFAULT NULL,
  PRICE_LIST SMALLINT DEFAULT NULL,
  PRODUCT_ID INT DEFAULT NULL,
  PRIORITY TINYINT DEFAULT NULL,
  PRICE DECIMAL(10,2) DEFAULT NULL,
  CURR VARCHAR(3) DEFAULT NULL
);
